
[target.'cfg(windows)']
rustflags = ["-C", "target-feature=+crt-static", "-Z", "threads=2"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[build]
rustflags = ["-Z", "threads=2"]
