[package]
name = "kfghdfghdfkgh_js_macros"
version = "1.0.0"
edition = "2021"
description = "This is an internal crate"
license = "MIT"

[lib]
crate-type = ["proc-macro"]

[dependencies]
quote = "1.0.37"
syn = "2.0.77"
