[package]
name = "ahqstore_service"
version = "1.2.0"
edition = "2021"
license = "Creative Commons Attribution Non Commercial 3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chacha20poly1305 = { version = "0.10.1", features = ["heapless"] }
futures-util = "0.3.28"
lazy_static = "1.4.0"
mslnk = "0.1.8"
reqwest = { version = "0.11.20", features = ["json"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
sysinfo = "0.29.10"
threadpool = "1.8.1"
tokio = { version = "1.32.0", default-features = false, features = ["net", "rt", "time"] }
tokio-tungstenite = "0.20.0"
windows-service = "0.6.0"
ahqstore-types = { path = "../ahqstore-types" }
