[package]
name = "ahqstore_service"
version = "1.3.6"
edition = "2021"
license = "Creative Commons Attribution Non Commercial 3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
reqwest = { version = "0.11.20", features = ["json"] }
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.105"
sysinfo = "0.30.0"
tokio = { version = "1.33.0", default-features = false, features = [
  "net",
  "rt",
  "time",
] }
ahqstore-types = { path = "../ahqstore-types" }

[target.'cfg(windows)'.dependencies]
mslnk = "0.1.8"
windows-service = "0.6.0"
chacha20poly1305 = { version = "0.10.1", features = ["heapless"] }
msi = "0.7.0"
winreg = "0.52.0"
windows = { version = "0.52.0", features = [
  "Win32_Foundation",
  "Win32_System_Pipes",
] }


[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true

[features]
sudo = ["no_service", "no_auth"]
no_service = []
no_auth = []
