import { VerticalBox, HorizontalBox, Button } from "std-widgets.slint";

export component InstallDialog inherits Window {
    min-height: 150px;
    max-height: 150px;

    min-width: 700px;
    max-width: 700px;

    VerticalBox {
      alignment: LayoutAlignment.stretch;

      HorizontalBox {
        Text {
          font-size: 30px;
          text: "Please select your install mode";
        }
      }
      HorizontalBox {
        Button {
          width: 300px;
          height: 30px;
          text: "APT (Debian Distros; Recommended)";
        }
        Button {
          width: 300px;
          height: 30px;
          text: "AppImage (Debian + Other Distros)";
        }
      }
    }
}